### PR TITLE
Redesign example site

### PR DESCRIPTION
**Pull request by merelinguist**
I saw your awesome plugin on the Gatsby Gazette, and thought the site could do with some design polish!

### Old:
screenshot_2019-01-05 https gatsby-source-google-scholar netlify com
 
### New:
screenshot_2019-01-05 gatsby google scholar use scientific publications in gatsby

Let me know what you think!

**Edit**: the build is fine on my end, but it looks like the api ran into a rate-limit!

### CODE REVIEW

**Comment by btk** [comment]
Looks really good 👍

**Comment by janosh** [comment]
@merelinguist Thanks for the PR! Looks great and will definitely be merged. Unfortunately, I only saw your PR after pushing a bunch of changes to add docs to the site so now there are merge conflicts. Could you pull down my changes and resolve the conflicts? If you don't have the time, I'll do it towards the end of next week.

**Comment by merelinguist** [comment]
Thanks, @janosh! I’ll try to resolve the conflicts soon.

**Comment by janosh** [comment]
@merelinguist Also, would you mind reintroducing some of the metadata? For sure the PDF link and the citation count are important.

**Comment by merelinguist** [comment]
For sure, working on it now. 👍

**Pull request closed without merging**
